### ISSUE TITLE
support for relative path for psalm.psalmScriptPath

### ISSUE THREAD

**Issue by shadowwa** [yaegassy/coc-psalm#12]
I have my vim config sync between several machine, some of them have a different path for $HOME.
psalm is installed globally on each machine (ie: ~/.config/composer/vendor/bin/psalm).

When I try to configure psalm.psalmScriptPath to a relative path:
```json
"psalm.psalmScriptPath": "$HOME/.config/composer/vendor/bin/psalm-language-server"
```
or
```json
"psalm.psalmScriptPath": "~/.config/composer/vendor/bin/psalm-language-server"
```

I got the message
```
[coc.nvim] The setting psalm.psalmScriptPath must be provided (e.g. vendor/bin/psalm-language-server)
```

to be able to make the psalm script detective I need to use absolute path
```json
"psalm.psalmScriptPath": "/home/user/.config/composer/vendor/bin/psalm-language-server"
```

which break on computer having a different $HOME, for example /homes/user/

**Comment by yaegassy** [comment]
Added support for `$HOME` and `~/`. Update `coc-psalm` and give it a try.

**Comment by shadowwa** [comment]
it's working fine with this patch, thank you.
