### ISSUE TITLE
Support for Psalm phar

### ISSUE THREAD

**Issue by still-dreaming-1** [yaegassy/coc-psalm#15]
It would be great if this could automatically work with or have a simpler option for working with Psalm as a phar. In the project I am working on, we install Psalm as a phar to avoid dependency compatibility issues. You are supposed to pass --language-server to the phar to use it as a language server. I can't seem to get it to work here, but it works in VSCode with no special configuration on our end.

**Comment by still-dreaming-1** [comment]
https://github.com/psalm/psalm-vscode-plugin/issues/33

**Comment by yaegassy** [comment]
In coc-psalm, `psalm` is invoked with the `--language-serer` option when the following is set in `coc-settings.json`.

```jsonc
{
  "psalm.psalmScriptPath": "/PATH/TO/psalm.phar",
}
```

However, it does not start with an error in my environment. I think the URL you posted also has a link to my issue report.

Also, in my environment, even if I configure `psalm.psalmScriptPath` with psalm-vscode-plugin in VSCode, the same error occurs and it does not start.

The `psalm.phar` I downloaded directly does not start. How did you prepare the `psalm.phar`?

**Comment by yaegassy** [comment]
By the way, it is possible to start psalm's language server without error if it is installed using composer in a different directory.

## Example

**Prepare**:

```
mkdir -p /tmp/psalm
cd /tmp/psalm
composer init -n --name dummy/dummy
composer require vimeo/psalm
```

**coc-setting.json**:

```
{
  "psalm.psalmScriptPath": "/tmp/psalm/vendor/bin/psalm",
}
```

**Comment by still-dreaming-1** [comment]
I'm going to try using Psalm the normal way without the phar as an experiment to find out if this is my real issue.

**Comment by still-dreaming-1** [comment]
It still didn't work at all for me even with just using Psalm installed the normal way, not as a phar. So whatever my issue is, it is not phar related. You can close this if you want. I'm not going to close it myself because it sounded like you may have confirmed it doesn't work with phars, but I'm not sure.
